TASK: change button style of AssetAction buttons too neutral
Flowpack/media-ui pull request #199
Opened 2023-08-04 19:46 UTC by crydotsnake

resolves: #198 

**What I did**

See: https://github.com/Flowpack/media-ui/issues/198

If the buttons are transparent it makes them a bit hard to see especially if you have a file with a white background, for example. And since the icons themselves Yes for example already have a white color. And on a transparent background that doesn't look nice.

Besides, it simply makes a nicer impression in my opinion.
But I am of course open to opinions !

**How I did it**

Changed the style of the AssetActions buttons from transparent too neutral.

**How to verify it**

### Before

![SCR-20230804-ssyq](https://github.com/Flowpack/media-ui/assets/39345336/18adaaff-4095-4bb1-b339-82bff8ef08f1)

### After
![SCR-20230804-srrh](https://github.com/Flowpack/media-ui/assets/39345336/23afe3c1-9886-4ccf-9806-71406436514e)

2023-08-14 08:29 UTC, Sebobo requested changes
This way you also change their look in the list of the media module. There I intentionally used the transparent versions.

That means you should set the button type as variable here and make it dependent on where it's being used.

2023-08-18 15:46 UTC, crydotsnake commented
I checked it with:

```ts
style={viewModeSelection === VIEW_MODES.List ? 'transparent' : 'neutral'}
```

But it still looks a little bit buggy too me 😕 
![Peek 2023-08-18 17-44](https://github.com/Flowpack/media-ui/assets/39345336/f78f45c5-ed02-4256-831a-714a945f9e6f)

I'm working on it.

2023-08-18 15:55 UTC, crydotsnake commented
Looks good! 🙂 

![new-behavior](https://github.com/Flowpack/media-ui/assets/39345336/c8f0785c-0b00-42d5-a30c-b11097f09ba4)

2023-09-11 08:39 UTC, Sebobo commented
Thx, will check it asap

2023-09-15 10:55 UTC, Sebobo commented
These examples don't look so good:

<img width="259" alt="Bildschirmfoto 2023-09-15 um 12 53 02" src="https://github.com/Flowpack/media-ui/assets/596967/0077d9b0-4091-4d44-81c7-8d058aac68ea">
<img width="293" alt="Bildschirmfoto 2023-09-15 um 12 52 25" src="https://github.com/Flowpack/media-ui/assets/596967/95d1d1be-de2e-4083-8254-8fe51edbceb3">

The buttons in thumbs view should remain transparent without hover. 
In the list mode the button position is not fully correct, you can see a little blue gap the the top. Maybe we should change the active and hover color, so there is a highlight on hover visible on the buttons. Do you want to try at a better solution with out color scheme?
We also have the color variants of the primary colors in our brand guide.

2023-09-15 10:55 UTC, Sebobo requested changes
See previous comment

2023-10-16 18:03 UTC, crydotsnake commented
> The buttons in thumbs view should remain transparent without hover.

I'm not sure if i understand you correctly, but why should they remain transparent? since this is exactly that i'm trying to improve here.

![SCR-20231016-rknn](https://github.com/Flowpack/media-ui/assets/39345336/166672cb-fdbc-48b6-aeba-a06e6469c555)

2023-10-16 18:29 UTC, crydotsnake commented
> The buttons in thumbs view should remain transparent without hover.

Hm. Like that? This also doesent look good IMO.. or maybe I have to give it a little time and think about it.


https://github.com/Flowpack/media-ui/assets/39345336/96113b75-4884-4665-9319-59cc0bb7eda7

2023-10-17 07:09 UTC, Sebobo commented
No, with your change there were not transparent by default anymore for me. I would prefer if they stay transparent "until" they are hovered. 
And in the list view they should still look good when the line is hovered and the background is therefore blue. That was also off like in my screenshot.l.

2026-04-14 08:46 UTC, closed without merging