FEATURE: Use custom transformer for flow exceptions
Flowpack/media-ui pull request #242
Opened 2024-10-23 17:05 UTC by markusguenther

The t3n GraphQL package includes a transformer that bypasses Flow Framework exceptions in GraphQL error handling. The error currently lacks the exception code as part of the information. By including this code (often a timestamp), we can render custom error messages in the backend and support localization.

<img width="1456" alt="Screenshot 2024-10-23 at 12 27 54" src="https://github.com/user-attachments/assets/47965602-737b-4762-a65a-0959325ec222">

Relates: #240

2024-10-23 17:06 UTC, markusguenther commented
It is not done yet but hopefully the idea is not so wrong.

2024-10-29 18:42 UTC, Sebobo requested changes
Still have to verify the change locally but thx already!

The German translation still needs some adjustments.

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Die übergeordnete Collection wurde gesetzt</target>
```suggestion
                <target>Die übergeordnete Sammlung wurde gesetzt</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Fehler beim Setzen der übergeordneten Collection</target>
```suggestion
                <target>Fehler beim Setzen der übergeordneten Sammlung</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Fehler beim Taggen der Collection</target>
```suggestion
                <target>Fehler beim Taggen der Sammlung</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Die Collection wurde getaggt</target>
```suggestion
                <target>Die Sammlung wurde getaggt</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Die Collections für die Datei wurden angepasst</target>
```suggestion
                <target>Die Sammlungen für die Datei wurden angepasst</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Fehler beim Anpassen der Collections für die Datei</target>
```suggestion
                <target>Fehler beim Anpassen der Sammlungen für die Datei</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Das angegebene Asset wurde nicht gefunden.</target>
```suggestion
                <target>Die angegebene Datei wurde nicht gefunden.</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Übergeordnetes Element muss eine Asset-Sammlung sein</target>
```suggestion
                <target>Übergeordnetes Element muss eine Sammlung sein</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Asset-Löschung fehlgeschlagen</target>
```suggestion
                <target>Datei-Löschung fehlgeschlagen</target>
```

2024-10-29 18:42 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Asset kann nicht aktualisiert werden, da es nie importiert wurde</target>
Please adjust `Asset` to `Datei` in German in the remaining file, and `collection` to `Sammlung`.

2024-10-29 19:25 UTC, markusguenther commented
Thanks for the feedback, updated the labels!

2024-11-01 13:20 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Fehler beim Aktualisieren der Collection</target>
```suggestion
                <target>Fehler beim Aktualisieren der Sammlung</target>
```

2024-11-01 13:21 UTC, Sebobo commented on Resources/Private/Translations/de/Main.xlf
> +                <target>Die Collection wurde aktualisiert</target>
```suggestion
                <target>Die Sammlung wurde aktualisiert</target>
```

2024-11-01 13:22 UTC, Sebobo approved these changes

2024-11-01 13:29 UTC, Sebobo commented
Hmm when I checkout the branch and build the module I now get 2 error messages:
![CleanShot 2024-11-01 at 14 29 05@2x](https://github.com/user-attachments/assets/85a50080-5baa-400a-a050-d9c68d20cd82)

2024-11-02 16:22 UTC, markusguenther commented
> Hmm when I checkout the branch and build the module I now get 2 error messages: ![CleanShot 2024-11-01 at 14 29 05@2x](https://private-user-images.githubusercontent.com/596967/382292262-85a50080-5baa-400a-a050-d9c68d20cd82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjQ3ODcsIm5iZiI6MTczMDU2NDQ4NywicGF0aCI6Ii81OTY5NjcvMzgyMjkyMjYyLTg1YTUwMDgwLTViYWEtNDAwYS1hMDUwLWQ5YzY4ZDIwY2Q4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxNjIxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGY3YTAxMTRhM2Q2MjQ4MjlhZjQ1NGFlNDE0Y2Q3NThiN2ViMDU5NzIxMDIwN2EzOThkMGRiZWUyNzY2YWMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YRlj3TIm5Y73w0Av0_iTQTvAuktJO6V6PBV_TO_yHhQ)

I guess that one error is thrown by the application itself and the other comes from the backend as a flash message.

2024-11-02 16:24 UTC, markusguenther commented
In the end with the PR https://github.com/Flowpack/media-ui/pull/241 that should not happen anymore.

2024-11-02 16:33 UTC, markusguenther commented
<img width="896" alt="Screenshot 2024-11-02 at 17 31 52" src="https://github.com/user-attachments/assets/3ca37b28-247c-4f43-8805-ec2c5ea7583f">

The behavior did not change, just the labels are different now and as I mentioned, with the validation before creating the tag we prevent having two flash messages.

2024-11-04 13:16 UTC, merged