FEATURE: get lastModified date from remote proxy
Flowpack/media-ui pull request #96
Opened 2021-10-29 10:03 UTC by pKallert

**What I did**
If an asset from a remote proxy is not imported, the last modified date is not used and defaults to 1.1.1970, 01:00:00 . With this PR, the last modified date from the remote asset source is used. 

**How I did it**
If there is no local asset, the function getLastModified is used to fetch the latest modify date. This function already exists in the AssetProxyInterface so it has to be implemented. I do not understand why the workaround with the localAssetData is used, so perhaps this can be generally replaced with the method from the interface? 

**How to verify it**
After integrating an asset source with remote assets (like https://github.com/flownative/neos-canto), the modified date does not default to 1.1.1970, 01:00:00. 
 
Closes #97

2021-11-03 16:38 UTC, kdambekalns approved these changes
Looks good to me, and I wonder about the check for `Asset`, too…

2021-11-04 07:51 UTC, Sebobo requested changes
Thx for spotting this. So we should be able to skip retrieving the local asset and just use the `getLastModified` of the proxy as you say. 

Can you adjust that?

2021-11-05 07:09 UTC, kdambekalns approved these changes

2021-11-05 12:35 UTC, Sebobo approved these changes

2021-11-05 12:47 UTC, merged